# Generated by Django 3.0.4 on 2020-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200407_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_filter',
            field=models.PositiveIntegerField(choices=[(0, 'none'), (1, 'love'), (2, 'life'), (3, 'family'), (4, 'friends'), (5, 'others')], default='0'),
        ),
    ]
