# Generated by Django 3.0.4 on 2020-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200408_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no',
            field=models.IntegerField(default=None),
        ),
    ]
